<?php

namespace Movibe\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BoxOfficeDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxOfficeDateRepository extends EntityRepository
{
    public function dateTroisMois()
    {
        $dates = $this->getEntityManager()->createQuery(
            'SELECT d
            FROM MovibeBackendBundle:BoxOfficeDate d
            ORDER BY d.dateBox DESC ')
            ->setMaxResults(12)
            ->getResult();

        foreach ($dates as $date)
        {
            $dateDebut = $date;
        }
        return $dateDebut;
    }

}
