<?php

namespace Movibe\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CinemaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CinemaRepository extends EntityRepository
{
    public function listDepartementByRegion($id)
    {
        $req = $this->getEntityManager()->createQuery('SELECT d FROM MovibeBackendBundle:Departement d WHERE d.region = :id ORDER BY d.nom')
                    ->setParameter('id', $id)->getResult();

        return $req;
    }

    public function listVilleByDepartement($id)
    {
        $req = $this->getEntityManager()->createQuery('SELECT v FROM MovibeBackendBundle:Ville v WHERE v.departement = :id ORDER BY v.nom')
            ->setParameter('id', $id)->getResult();

        return $req;
    }

    public function getVille($id)
    {
        $req = $this->getEntityManager()->createQuery('SELECT v FROM MovibeBackendBundle:Ville v WHERE v.id = :id')
            ->setParameter('id',$id)->getSingleResult();
        return $req;
    }
}
