<?php

namespace Movibe\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementRepository extends EntityRepository
{
    public function listDepartementByRegion($id)
    {
        $req = $this->getEntityManager()->createQuery('SELECT d FROM MovibeBackendBundle:Departement d WHERE d.region = :id ORDER BY d.nom')
            ->setParameter('id', $id)->getResult();

        return $req;
    }
}
