<?php

namespace Movibe\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MetierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetierRepository extends EntityRepository
{
    public function showMetiers()
    {
        return $this->createQueryBuilder('m')->where('m.parent IS NOT NULL')->getQuery()->getResult();
    }

    public function showParents()
    {
        return $this->createQueryBuilder('m')->where('m.parent IS NULL')->getQuery()->getResult();
    }

    public function metierActeurs()
    {
        return $this->createQueryBuilder('m')->where('m.parent = 5');
    }

    public function metierRealisateurs()
    {
        return $this->createQueryBuilder('r')->where('r.parent = 6');
    }

    public function metierScenaristes()
    {
        return $this->createQueryBuilder('s')->where('s.parent = 2');
    }

    public function metierProducteurs()
    {
        return $this->createQueryBuilder('p')->where('p.parent = 1');
    }

    public function metierEquipeTechnique()
    {
        return $this->createQueryBuilder('e')->where('e.parent = 3');
    }

    public function metierDistributeurs()
    {
        return $this->createQueryBuilder('d')->where('d.parent = 58');
    }

    public function metierCompositeurs()
    {
        return $this->createQueryBuilder('d')->where('d.parent = 59 ');
    }

    public function metierSocietes()
    {
        return $this->createQueryBuilder('s')->where('s.parent = 4 ');
    }
}
