<?php

namespace Movibe\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysRepository extends EntityRepository
{
    public function filePaysUpload($pays_list)
    {
        $dir = __DIR__ . '/../../../../web/bundles/movibebackend/js/vendors/bootstrap-form-helpers';
        $fichier = $dir . "/bootstrap-formhelpers-countries.fr_FR.js";

        $fp = fopen($fichier,"w");
        if($fp==false)
        {
            return false;
        }
        else
        {
            fwrite($fp,"var BFHCountriesList = {\n");
            foreach ($pays_list as $pays)
            {
                fwrite($fp,'  "' . $pays->getCode() . '": "' . $pays->getNom() . '",' . "\n");
            }
            fwrite($fp,"};");
            fclose($fp);
            return true;
        }
    }

}
