<?php

namespace Movibe\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeanceRepository extends EntityRepository
{
    public function seanceByElement($type, $idt)
    {
        switch ($type)
        {
            case 'film':
                $req = $this->getEntityManager()->createQuery('SELECT s FROM MovibeBackendBundle:Seance s WHERE s.film = :idt')
                    ->setParameter('idt', $idt)->getResult();
                break;
            case 'cinema':
                $req = $this->getEntityManager()->createQuery('SELECT s FROM MovibeBackendBundle:Seance s WHERE s.cinema = :idt')
                    ->setParameter('idt', $idt)->getResult();
                break;
        }
        return $req;
    }
}
