<?php

namespace Movibe\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends EntityRepository
{
    public function showAll()
    {
        $req = $this->getEntityManager()->createQuery('SELECT v FROM MovibeBackendBundle:Ville v')->setMaxResults(1000);

        return $req->getResult();

    }

    public function listVilleByDepartement($id)
    {
        $req = $this->getEntityManager()->createQuery('SELECT v FROM MovibeBackendBundle:Ville v WHERE v.departement = :id ORDER BY v.nom')
            ->setParameter('id', $id)->getResult();

        return $req;
    }

    public function getVille($id)
    {
        $req = $this->getEntityManager()->createQuery('SELECT v FROM MovibeBackendBundle:Ville v WHERE v.id = :id')
            ->setParameter('id',$id)->getSingleResult();
        return $req;
    }
}
