movibe_backend_couleur:
    path:     /
    defaults: { _controller: MovibeBackendBundle:Couleur:index }


movibe_backend_couleur_new:
    path:     /couleur_new
    defaults: { _controller: MovibeBackendBundle:Couleur:new }

movibe_backend_couleur_create:
    path:     /couleur_create
    defaults: { _controller: MovibeBackendBundle:Couleur:create }
    requirements:
        _method: POST

movibe_backend_couleur_show:
    path:     /couleur_show/{id}
    defaults: { _controller: MovibeBackendBundle:Couleur:show }
    requirements:
        id: \d+

movibe_backend_couleur_edit:
    path:     /couleur_edit/{id}
    defaults: { _controller: MovibeBackendBundle:Couleur:edit }
    requirements:
        id: \d+

movibe_backend_couleur_update:
    path:     /couleur_update/{id}
    defaults: { _controller: MovibeBackendBundle:Couleur:update }
    requirements:
        _method: POST
        id: \d+

movibe_backend_couleur_delete:
    path:     /couleur_delete/{id}
    defaults: { _controller: MovibeBackendBundle:Couleur:delete }
    requirements:
        _method: GET|DELETE
        id: \d+
