movibe_backend_typeFilm:
    path:     /
    defaults: { _controller: MovibeBackendBundle:TypeFilm:index }


movibe_backend_typeFilm_new:
    path:     /typeFilm_new
    defaults: { _controller: MovibeBackendBundle:TypeFilm:new }

movibe_backend_typeFilm_create:
    path:     /typeFilm_create
    defaults: { _controller: MovibeBackendBundle:TypeFilm:create }
    requirements:
        _method: POST

movibe_backend_typeFilm_show:
    path:     /typeFilm_show/{id}
    defaults: { _controller: MovibeBackendBundle:TypeFilm:show }
    requirements:
        id: \d+

movibe_backend_typeFilm_edit:
    path:     /typeFilm_edit/{id}
    defaults: { _controller: MovibeBackendBundle:TypeFilm:edit }
    requirements:
        id: \d+

movibe_backend_typeFilm_update:
    path:     /typeFilm_update/{id}
    defaults: { _controller: MovibeBackendBundle:TypeFilm:update }
    requirements:
        _method: POST
        id: \d+

movibe_backend_typeFilm_delete:
    path:     /typeFilm_delete/{id}
    defaults: { _controller: MovibeBackendBundle:TypeFilm:delete }
    requirements:
        _method: GET|DELETE
        id: \d+
