security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles:'ROLE_ADMIN' }
                    user: { password: user, roles: 'ROLE_USER' }

        fos_userbundle:
            id: fos_user.user_provider.username

        mixte:
            chain:
                providers: [in_memory, fos_userbundle]

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: mixte
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            provider: mixte
            switch_user: true
            pattern: ^/
            form_login:
                login_path: /login
                check_path: /login_check
                csrf_provider: form.csrf_provider  #pour FOSUser
            logout:
                path: /logout
            anonymous: true

    access_control:
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/js, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_ADMIN }


